scan:
  src:
      - common\src\main\java
      - contest\src\main\java
      - practice\src\main\java
      - advice\src\main\java
      - sys\src\main\java
      - user\src\main\java
root:
  - E:\projects\LeTucOJ\

method:
  - com.LetucOJ.common.result.Result
